server:
  port: 8080

spring:
  application:
    name: asset-management-system

  datasource:
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true